# MYSQL
    SQLALCHEMY_DATABASE_URI = "mysql+pymysql://root:Cgy005688@sh-cynosdbmysql-grp-kuvfpbfg.sql.tencentcdb.com:25736/jobs?charset=utf8mb4"

# MONGODB
MONGO_URI = 'mongodb://localhost:27017/jobs'

# EMAIL
MAIL_SERVER = 'smtp.qq.com'
MAIL_PORT = 465
MAIL_USE_TLS = false
MAIL_USE_SSL = true
MAIL_DEBUG = true
MAIL_USERNAME = "422736002@qq.com"
MAIL_PASSWORD = "kasxtzileefcbifa"
MAIL_DEFAULT_SENDER = "422736002@qq.com"

# JWT
JWT_SECRET_KEY = 'HHH'

# OTHER
JSON_AS_ASCII = false
SECRET_KEY = 'hhhhhhhh'
SALT = 'jjjj'
TEMPLATES_AUTO_RELOAD = true
SEND_FILE_MAX_AGE_DEFAULT = 0
SQLALCHEMY_TRACK_MODIFICATIONS = true

# COS
COS_SECRET_ID = "AKIDRhhQs3xaw1qOfwxg8JDqCH4apnUu3vWq"
COS_SECRET_KEY = "4sOdbIirjKehTyC8nBJAk34oHTN0MRFm"
COS_REGION = "ap-nanjing"
COS_BUCKET = "byszqq-1310478750"
